import './globals.css'
import Header from './navbar'
export const metadata = {
  title: 'AR | FullStack Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header></Header>
        {children}
        </body>
    </html>
  )
}
